# Generated by Django 3.0.4 on 2020-06-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0003_auto_20200608_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out On Delivery', 'Out On Delivery')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Phone Accessories', 'Phone Accessories'), ('Laptops', 'Laptops'), ('Laptop Accessories', 'Laptop Accessories'), ('Phones', 'Phones')], default='Phones', max_length=150),
        ),
    ]
